### ISSUE TITLE
Functional `SearchBar/AutoSuggestBox`

### ISSUE THREAD

**Issue by lknknm** [lknknm/REZ-menu-app#16]
### Descrição 
Precisamos implementar a funcionalidade correta da SearchBar para que ao digitar seja possível achar os itens do cardápio.
A SearchBar é comandada pela `AutoSuggestBox` presente nos arquivos `*.xaml`. Seria importante integrá-la com a pesquisa para que ao pesquisar, seja mostrado o item corretamente na `ListView`.

![Image](https://user-images.githubusercontent.com/108239558/260867273-fd75a73e-d88a-430d-a430-92f8a3bc8307.png)

### Mais detalhes:
A documentação da `AutoSuggestBox` está no aplicativo do WinUI pelo link: winui3gallery://item/AutoSuggestBox
E por este link para a API: https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.autosuggestbox
Precisamos ver como fazer para que, ao digitar, a `ListView` com o cardápio seja atualizada. Acho que no aplicativo WinUI Gallery deve ter mais exemplos.

**Comment by andavgc** [comment]
A PR #30 resolve essa issue
