### ISSUE TITLE
Functional `ShoppingCart`

### ISSUE THREAD

**Issue by lknknm** [lknknm/REZ-menu-app#17]
### Descrição
Precisamos fazer com que o `ShoppingCart` seja atualizado conforme as informações de cada `User`.
Minha ideia é que quando o ShoppingCart do usuário está vazio, o seguinte `TeachingTip` seja mostrado:

![Image](https://github.com/lknknm/REZ-menu-app/assets/108239558/ba1b256b-650c-4f2e-a9f6-0272485b2ce4)

```xaml
               <TeachingTip x:Name="ToggleThemeTeachingTip1"
                   Target="{x:Bind ShoppingCartButton}"
                   Title="Your shopping cart is empty."
                   Subtitle="Add items to your order to display them here.">
               </TeachingTip>
```

Mas quando o `ShoppingCart` de um usuário tem pelo menos um item, ele mostrará o `ShoppingCartModal.xaml` com uma `ListView` dos itens selecionados, campo de divisão de contas com outros usuários da mesa, opção para adicionar ao carrinho, Subtotal e Total do pedido.

![Image](https://github.com/lknknm/REZ-menu-app/assets/108239558/e67683c4-8f33-4d76-8c81-e5347dff4998)
No momento essas informações estão HardCoded para demonstração, mas agora precisamos puxar esses dados do Back-End para que a integração do carrinho faça sentido. Com isso, também precisamos que, ao apertar o botão de confirmar pedido, o mesmo seja enviado para o servidor/"cozinha" (inclusive talvez abrindo outro modal com o número do pedido).

**Comment by andavgc** [comment]
O PR #22 resolveu este issue
