### ISSUE TITLE
Functional `MainPage` Menu Buttons

### ISSUE THREAD

**Issue by lknknm** [lknknm/REZ-menu-app#18]
### Descrição
Na página principal do aplicativo, os botões que estão embaixo devem redirecionar para a categoria específica da próxima página. No momento o aplicativo está apenas redirecionando o usuário para a página de cardápio, sem diferenciação entre qual botão foi clicado na página principal e qual categoria deverá ser mostrada.

![Image](https://user-images.githubusercontent.com/108239558/261158456-7bc291c0-70fa-4e18-b2c0-01e628693380.png)

![Image](https://user-images.githubusercontent.com/108239558/261158499-12d1dd20-e321-49ef-a779-f2b7b0fea5b4.png)

Precisamos fazer com que, ao clicar o botão específico da categoria na página principal, o usuário seja redirecionado diretamente a ela na página do cardápio.

**Comment by andavgc** [comment]
A PR #30 resolve essa issue
