### ISSUE TITLE
Definir o problema do usuário

### ISSUE THREAD

**Issue by andavgc** [lknknm/REZ-menu-app#4]
### Descrição
Precisamos definir o problema do usuário e a jornada de usuário.
Estou iniciando um rascunho no docs abaixo:
https://docs.google.com/document/d/1ifUERHIx9T09bU9mYd4IYp_RpjMFvlLVONY8YNQeMRA/edit

**Comment by lknknm** [comment]
Coloquei o arquivo do Google Drive dentro da pasta `./docs` do projeto no commit 9726c90.
